### ISSUE TITLE
How to use THEOplayer without the player options like play/ pause, seek, fullscreen?

### ISSUE THREAD

**Issue by mohitbhansali** [THEOplayer/react-native-project#1]
Requirement: I would like to build the custom player options, is it possible?

**Comment by PooriaN** [comment]
I guess you can use this document: https://github.com/THEOplayer/react-native-project/tree/master/08-rn-custom-ui

**Comment by savdeepgandhi13** [comment]
Do you mean that you wish to change the UI of the THEOplayer or change the default UI. You can do that by either using our Chromeless UI library or use our default to overwrite the current CSS by injecting the js file. You can use the CustomUI project to see how to do that.
